config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.conf import settings

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('', include('spa.urls', namespace='spa')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spa/urls.py
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from django.conf.urls.static import static
from django.urls import path, include

from config import settings
from spa.apps import SpaConfig
from spa.form_set import ProfileListWithPayment
#from spaform_set import ProfileListWithUserSubscription ##CustomUserListWithUserSubscription,
from spa.views import SigninView, SignupView, CourseViewSet, LessonListAPIView, LessonUpdateView, \
    LessonCreateAPIView, LessonRetrieveUpdateDestroy, PayListAPIView, \
    PayCustomUserDetailAPIView, PayRetrieveUpdateDestroyAPIView, \
    ProfileViewSet, PaymentCheckView, PayListCheckAPIView, CourseUpdateView, UserSubscriptionAPIView, \
    UserSubscriptionViewSet
# , CourseCreateAPIView
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
#CourseListView,
app_name = SpaConfig.name##Ne pokazal nam obyavlenia prilozhenia
router = DefaultRouter()
router.register(r'home', CourseViewSet.as_view({'get': 'list'}), basename='home')

urlpatterns = [
               path('', SigninView.as_view(template_name='spa/login.html'), name='login'),
               path('register', SignupView.as_view(template_name='spa/register.html'), name='register'),
               path('home/', CourseViewSet.as_view({'get': 'list'}), name='home_course_view'),#template_name='spa/home.html'
               # path('home/', CourseCreateAPIView.as_view(), name='home'),
               path('home/course_create/', CourseViewSet.as_view({ "post": "create"}), name='home'),#template_name='spa/course_list.html'###,"get": "retrieve", "put": "update", "patch": "partial_update", "delete": "destroy"
               path('home/course_list/update/<int:pk>', CourseUpdateView.as_view(), name='course_update'),
               path('home/lesson_list/', LessonListAPIView.as_view(), name='lesson_list'),
               path('home/lesson_list/create/', LessonCreateAPIView.as_view(), name='lesson_create'),
               path('home/lesson_list/update/<int:pk>', LessonUpdateView.as_view(), name='lesson_update'),
               #path('home/lesson_list/<int:pk>', LessonRetrieveView.as_view(), name='lesson_update'),
               path('home/lesson_detail/<int:pk>', LessonRetrieveUpdateDestroy.as_view(), name='lesson_RetrieveUpdateDestroy'),
               path('pay_list/', PayListAPIView.as_view()),
                path('pay_list_check/', PayListCheckAPIView.as_view()),#Proveryaem platezh

               path('pay/<int:pk>', PayCustomUserDetailAPIView.as_view()),
               path('pay_update/<int:pk>', PayRetrieveUpdateDestroyAPIView.as_view()),

               path('home/UserSubscription/', UserSubscriptionViewSet.as_view({'get': 'list', "post": "create", "delete": "destroy"})),
               # path('home/UserSubscription/<int:pk>', UserSubscriptionViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update', 'delete': 'destroy'})),
               path('home/UserSubscriptionChange/', UserSubscriptionAPIView.as_view(), name='subscription'),# UserSubscriptionAPIView
               path('home/Profile/', ProfileViewSet.as_view({'get': 'list', "post": "create", "delete": "destroy"})),
               path('home/Profile/<int:pk>', ProfileViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),
               path('home/ProfileWithCourse/', ProfileListWithPayment.as_view()),##Zdes novie polya mozhno dobavlyat ot UserSubscription
               path('PaymentCheck/<int:pk>', PaymentCheckView.as_view(), name='paymentcheck'),

               path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
               path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
               ]
              # + router.urls
#
#     [
#     ,
#
#
# ]

spa/models.py
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# from pkg_resources import _
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny

import spa

NULLABLE = {'blank': True, 'null': True}
# UserManager
# class CustomUserManager(UserManager):
#
#     def create_superuser(self, email=None, password=None, **extra_fields):
#         extra_fields.setdefault("is_staff", True)
#         extra_fields.setdefault("is_superuser", True)
#
#         if extra_fields.get("is_staff") is not True:
#             raise ValueError("Superuser must have is_staff=True.")
#         if extra_fields.get("is_superuser") is not True:
#             raise ValueError("Superuser must have is_superuser=True.")
#
#         return self._create_user(email, password, **extra_fields)
#
#     def _create_user(self, email, password, **extra_fields):
#         if not email:
#             raise ValueError("The given email must be set")
#         email = self.normalize_email(email)
#         user = self.model(email=email, **extra_fields)
#         user.password = make_password(password)
#         user.save(using=self._db)
#         return user

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
# from phonenumber_field.modelfields import PhoneNumberField
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = None
    # firstname = models.CharField(max_length = 60)
    # lastname = models.CharField(max_length = 60)
    email = models.EmailField(max_length=240, unique=True)
    # phone = PhoneNumberField(null=True, blank=True)
    # company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, blank=True)
    password = models.CharField(max_length=240)
    # is_staff = models.BooleanField(_('staff status'), default=False)
    is_staff = models.BooleanField('staff status', default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['password']  # 'firstname', 'lastname',

    objects = CustomUserManager()

    # user_permissions = None
    # groups = None
    def __str__(self):
        return self.email


# class User(AbstractUser):
# objects = CustomUserManager()

# verify_token = models.CharField(max_length=35, verbose_name='Токен верификации',
#                                 **NULLABLE)
# verify_token_expired = models.DateTimeField(**NULLABLE,
#                                             verbose_name='Дата истечения токена')
# new_password = models.CharField(verbose_name="новый пароль", max_length=128, **NULLABLE)
# username = None
# email = models.EmailField(
#     verbose_name='Почта',
#     unique=True
# )
# phone = models.CharField(max_length=20, verbose_name='телефон', **NULLABLE)
# city = models.CharField(max_length=35, verbose_name='город',**NULLABLE)
# avatar = models.ImageField(upload_to='media/', verbose_name='аватарка',**NULLABLE)
# USERNAME_FIELD = 'email'
# REQUIRED_FIELDS = []

# def __str__(self):
#         return f'{self.email} '#{self.avatar} {self.city}{self.phone}

class Lesson(models.Model):
    name = models.CharField(max_length=35, verbose_name='название урока', **NULLABLE)
    preview = models.CharField(max_length=50, **NULLABLE)
    smth = models.ForeignKey('spa.Course', on_delete=models.CASCADE, related_name='smthin', **NULLABLE)
    description = models.CharField(max_length=350, verbose_name='описание урока', **NULLABLE)
    reference = models.CharField(max_length=55, **NULLABLE, verbose_name='ссылка на видео')
    price = models.IntegerField(default=1000)

    class Meta:
        verbose_name = 'урок'
        verbose_name_plural = 'уроки'

    def __str__(self):
        return f'{self.name} {self.description}{self.smth} '  ## {self.reference}{self.preview}


class Course(models.Model):
    name = models.CharField(max_length=35, verbose_name='название курса', **NULLABLE)
    preview = models.CharField(max_length=50, verbose_name=' фото урока', **NULLABLE)
    description = models.TextField(max_length=300, verbose_name='описание курса', **NULLABLE)
    pro_file = models.ForeignKey('spa.Profile', on_delete=models.CASCADE, **NULLABLE)

    # pro_file = GenericRelation('profile')##Dostup k profile cherez Course

    class Meta:
        verbose_name = 'курс'
        verbose_name_plural = 'курсы'

    def __str__(self):
        return f'{self.name}{self.preview}  {self.description}'


# def check_for_change(instance):
#     try:
#         course = Course.objects.get(id=instance.id)
#     except Course.DoesNotExist:
#         return  None
# default_permission = [AllowAny]
# permissions = {
#     "list": [IsAuthenticated],
#     "retrieve": [IsAdminUser]
# }
# def get_permissions(self):
#     return [perm() for perm in self.permissions.get(self.action, self.default_permission)]

class Payment(models.Model):
    PAYMENT_CARD = 'card'
    PAYMENT_CASH = 'cash'
    PAY_FORMS = (
        (PAYMENT_CARD, 'перевод на счет'),
        (PAYMENT_CASH, 'наличные')
    )

    pro_filee = models.ForeignKey('spa.Profile', verbose_name='пользователь', on_delete=models.CASCADE, default=0,
                                  db_constraint=False)  # settings.AUTH_USER_MODEL,
    date_of_payment = models.DateTimeField(verbose_name='дата оплаты', **NULLABLE)
    lesson = models.ForeignKey('spa.Lesson', on_delete=models.CASCADE, related_name="lesson", verbose_name='урок',
                               **NULLABLE, db_constraint=False)  # db_constraint=False
    course = models.ForeignKey('spa.Course', on_delete=models.CASCADE, related_name="course", verbose_name='курс',
                               **NULLABLE, db_constraint=False)
    sum_of_payment = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='сумма оплаты')
    form_of_payment = models.CharField(max_length=10, choices=PAY_FORMS, default=PAYMENT_CARD,
                                       verbose_name='способ оплаты наличные или перевод')
    # PaymentURL = models.CharField(max_length=50, verbose_name= "ссылка на оплату")
    Success = models.CharField(max_length=50, verbose_name="Статус обработки", null=True)
    ErrorCode = models.CharField(max_length=50, verbose_name="Ошибка", null=True)
    Message = models.CharField(max_length=50, verbose_name="Сообщение", null=True)
    Details = models.CharField(max_length=50, verbose_name="Детали", null=True)
    TerminalKey = models.CharField(max_length=50, verbose_name="Детали", null=True)
    Status = models.CharField(max_length=50, verbose_name="Детали", null=True)
    PaymentId = models.CharField(max_length=50, verbose_name="Номер платежа", null=True)
    OrderId = models.CharField(max_length=50, verbose_name="Номер заказа", null=True)
    Amount = models.CharField(max_length=50, verbose_name="Сумма", null=True)
    PaymentURL = models.CharField(max_length=50, verbose_name="Ссылка на оплату", null=True)

    def __str__(self):
        return f' {self.sum_of_payment}'  # {self.pro_filee}

    class Meta:
        verbose_name = 'платеж'
        verbose_name_plural = 'платежи'


PERIOD_DAY = 86400
PERIOD_WEEK = 604800
PERIOD_MONTH = 2419200

PERIODS = (
    (PERIOD_DAY, 'день=86400'),
    (PERIOD_WEEK, 'неделя=604800'),
    (PERIOD_MONTH, 'месяц=2419200'),
)
STATUS_DONE = False
STATUS_START = True

STATUSES = (
    (STATUS_DONE, False),
    (STATUS_START, True),
)


class UserSubscription(models.Model):
    profile = models.ForeignKey('spa.Profile', on_delete=models.CASCADE)  ##Nelzya FK esli uzhe est M2M???
    course_subscribe = models.ForeignKey('spa.Course', on_delete=models.CASCADE, **NULLABLE)
    lesson_subscribe = models.ForeignKey('spa.Lesson', on_delete=models.CASCADE, **NULLABLE)
    status = models.BooleanField(choices=STATUSES, default=STATUS_START)  ##Podpisan ili net
    status_send = models.BooleanField(choices=STATUSES, default=STATUS_START)  ##Otoslano ili net
    subscribed_on = models.DateTimeField(auto_now_add=True)  ##auto_created=?????????
    period = models.TimeField(auto_now=True, max_length=10, choices=PERIODS, **NULLABLE)

    class Meta:
        # ordering = ('user',)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return f'{self.profile} {self.course_subscribe} {self.lesson_subscribe} {self.status} {self.subscribed_on} {self.period}'


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name='Профиль', on_delete=models.CASCADE)
    email = models.CharField(max_length=240, unique=False, **NULLABLE)
    title = models.CharField(max_length=60, verbose_name='наименование')
    slug = models.SlugField(verbose_name='Персональная ссылка', unique=True, max_length=255, **NULLABLE)
    bio = models.TextField(max_length=500, verbose_name='Информация о себе', blank=True)
    # content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)###Tri polya sviazivaut Profile so vsemi modeliami voobshe
    # content_id = models.PositiveIntegerField()
    # content_object = GenericForeignKey('content_type', 'object_id')
    avatar = models.ImageField(
        verbose_name='Аватар профиля',
        blank=True,
        upload_to='media/',
        validators=[FileExtensionValidator(
            allowed_extensions=('png', 'jpg', 'webp', 'jpeg'))
        ]
    )
    date_birthday = models.DateField(verbose_name='Дата рождения', blank=True, null=True)
    # following_subscription = models.ManyToManyField('spa.UserSubscription', verbose_name='Подписки',

spa/templates/spa/Product_list.html
{% extends 'catalog/base.html' %}
    {% block content %}
<h1>Category</h1>
  <table class="table table-dark table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Category</th>
              <th scope="col">Category Description</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
<!--                {% if object.category != "nasekomie" %}-->
                <tr>
                    <td>{{object.id}}</td>
                    <td>{{object.category}}</td>
                    <td>{{object.category_description}}</td>

                </tr>
<!--                {% endif %}-->
          {% endfor %}
          </tbody>
        </table>
<!--https://pickimage.ru/wp-content/uploads/images/detskie/orange/apelsin8.jpg-->
<div class="card" style="width: 18rem;">
  <img src="/media/grocery_delivery.avif" width="10" height="200" class="card-img-top" alt="Lemon">
  <div class="card-body">
    <p class="card-text">Gentle groceries from friendly people, hm... friendly groceries from gentle people</p>
  </div>
</div>

    {% load filter_catalog %}

<h1>Products</h1>
          <table class="table table-dark table-striped">
          <thead>
            <tr>
                <th scope="col">Details</th>
                <th scope="col">№</th>
                <th scope="col">Product Name</th>
                <th scope="col">Preview</th>
                <th scope="col">Product Description</th>
                <th scope="col">Product Category</th>
                <th scope="col">Price of Unit</th>
                <th scope="col">Status</th>
                <th scope="col">Make choice</th>
            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>
                    <a class="btn btn-outline-light w-50" href="{% url 'catalog:Product_detail' object.pk %}"></a>


                    <td>{{object.id}}</td>
                    <td> {{ object.product_name|truncatechars:5 }} </td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>
                    <td>{{object.product_description}}</td>
                    <td>{{object.category}}</td>
                    <td>{{object.price_per_unit}}</td>

                    <td>{{object.get_status_display}}
                        {% if perms.catalog.set_published_status %}
                            {% if object.published_status %}

                                <a class="btn btn-light" href="{% url 'catalog:status' object.pk %}">X</a>
                                {% else %}
                                <a class="btn btn-light" href="{% url 'catalog:status' object.pk %}">V</a>
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        <a class="btn.btn-default" href="{% url 'catalog:Product_form' object.pk %}" >Update</a>
                        {% if perms.catalog.create_Product %}
                            <a class="btn.btn-default" href="{% url 'catalog:Product_create' object.pk %}" >Create</a>
                        {% endif %}
                        {% if perms.catalog.delete_products %}
                            <a class="btn.btn-default" href="{% url 'catalog:Product_delete' object.pk %}" >Delete</a>
                        {% endif %}

                    </td>

                    </td>
                </tr>

          {% endfor %}

          </tbody>
        </table>
<h1> {{g}}</h1>
    {% endblock %}

spa/templates/spa/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Signin Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        html,
        body {
            height: 100%;
        }

        body {
            display: flex;
            align-items: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
        }

        .form-signin .form-floating:focus-within {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

</head>
<body class="text-center">

<main class="form-signin w-100 m-auto">
    <h2>***************</h2>
    {% block content %}
    {% endblock %}
    <p class="mt-5 mb-3 text-muted">&copy; 2023–{% now 'Y' %}</p>
</main>


</body>
</html>

spa/templates/spa/course_list.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>

                 <th scope="col">фото курса</th>

                <th scope="col">описание курса</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>


                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

spa/templates/spa/home.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>
                <th scope="col">описание курса</th>
                <th scope="col">фото курса</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>
                <th scope="col">фото урока</th>
            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>
                    <td>{{object.price_per_unit}}</td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}
~

spa/templates/spa/lesson_create.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
              <td>
                        <a class="btn.btn-default" href="{% url 'catalog:Product_form' object.pk %}" >Update</a>
                        {% if perms.catalog.create_Product %}
                            <a class="btn.btn-default" href="{% url 'catalog:Product_create' object.pk %}" >Create</a>
                        {% endif %}
                        {% if perms.catalog.delete_products %}
                            <a class="btn.btn-default" href="{% url 'catalog:Product_delete' object.pk %}" >Delete</a>
                        {% endif %}

              </td>
            <tr>

                <th scope="col">название курса</th>

                 <th scope="col">фото урока</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>
                    <td>{{object.price_per_unit}}</td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

spa/templates/spa/lesson_delete.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>

                 <th scope="col">фото урока</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>
                    <td>{{object.price_per_unit}}</td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

spa/templates/spa/lesson_list.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>

                 <th scope="col">фото урока</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>
                    <td>{{object.price_per_unit}}</td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

spa/templates/spa/lesson_update.html
{% extends 'spa/base.html' %}
{% block content %}
  <h2 class="display-6 text-center mb-6">SPA</h2>
{{object_list}}
 <table class="table table-light table-striped table-hover align-items-center  text-center">
          <thead>
            <tr>

                <th scope="col">название курса</th>

                 <th scope="col">фото урока</th>
                <th scope="col">название урока</th>
                <th scope="col">описание урока</th>

            </tr>
          </thead>
          <tbody>
           {% for object in object_list %}
                <tr>
                    <td>

                    <td>{{object.name}}</td>

                    <td>
                        <img src="/media/{{object.preview}}"  width="50" height=50  alt=""/>

                    </td>

                    <td>{{object.description}}</td>
                    <td>{{object.price_per_unit}}</td>

                </tr>

          {% endfor %}

          </tbody>
        </table>
{% endblock %}

spa/templates/spa/login.html
{% extends 'spa/base.html' %}
{% block content %}
    <h1>Login</h1>
    <hr>
    {% if form.errors %}
        <p>{{ form.errors.error }}</p>
    {% endif %}
    <form action="{% url 'spa:login' %}" method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Submit</button>
    </form>
    <a href="{% url 'spa:register' %}">Нет аккаунта</a>
{% endblock %}
~

spa/templates/spa/paymentform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

spa/templates/spa/register.html
{% extends 'spa/base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Зарегистрируйтесь</h1>
        {{ form.as_p }}
        <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
        <a class="btn btn-link" href="{% url 'spa:login' %}">Есть аккаунт?</a>
    </form>

{% endblock %}